---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
