//-----------------------------------------------------------------------------
// DO NOT EDIT THIS FILE!
// This is generated by wise_units-atom_generator.
//-----------------------------------------------------------------------------

use crate::parser::symbols::symbol_parser::Rule;
use crate::parser::symbols::Symbol;
use crate::parser::{Atom, Error, Prefix};
use pest::iterators::Pair;

pub(in super::super) fn map(pair: Pair<'_, Rule>) -> Result<Symbol, Error> {
    fn visit_pairs(pair: Pair<'_, Rule>) -> Result<Symbol, Error> {
        let symbol = if let Rule::symbol = pair.as_rule() {
            visit_symbol(pair)?
        } else {
            let error = Error::UnableToParse {
                expression: pair.as_str().to_string(),
            };

            return Err(error);
        };

        Ok(symbol)
    }

    let symbol = visit_pairs(pair)?;

    Ok(symbol)
}

fn visit_symbol(pair: Pair<'_, Rule>) -> Result<Symbol, Error> {
    let mut prefix: Option<Prefix> = None;
    let mut atom: Option<Atom> = None;

    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::pri_prefix | Rule::sec_prefix => {
                let next = inner_pair
                    .into_inner()
                    .next()
                    .expect("Unable to get next prefix");
                prefix = Some(visit_prefix(&next)?);
            }
            Rule::pri_atom | Rule::sec_atom => {
                let next = inner_pair
                    .into_inner()
                    .next()
                    .expect("Unable to get next atom");

                atom = Some(visit_atom(&next)?);
            }
            _ => {
                let error = Error::UnableToParse {
                    expression: inner_pair.as_str().to_string(),
                };

                return Err(error);
            }
        }
    }

    Ok(Symbol { prefix, atom })
}

fn visit_atom(pair: &Pair<'_, Rule>) -> Result<Atom, Error> {
    let atom = match pair.as_rule() {
        Rule::pri_acre_british | Rule::sec_acre_british => Atom::AcreBritish,
        Rule::pri_acre_us | Rule::sec_acre_us => Atom::AcreUS,
        Rule::pri_allergen_unit | Rule::sec_allergen_unit => Atom::AllergenUnit,
        Rule::pri_allergen_unit_for_ambrosia_artemisiifolia
        | Rule::sec_allergen_unit_for_ambrosia_artemisiifolia => {
            Atom::AllergenUnitForAmbrosiaArtemisiifolia
        }
        Rule::pri_ampere | Rule::sec_ampere => Atom::Ampere,
        Rule::pri_angstrom | Rule::sec_angstrom => Atom::Angstrom,
        Rule::pri_anti_factor_xa_unit | Rule::sec_anti_factor_xa_unit => Atom::AntiFactorXaUnit,
        Rule::pri_apl_unit | Rule::sec_apl_unit => Atom::AplUnit,
        Rule::pri_arbitary_unit | Rule::sec_arbitary_unit => Atom::ArbitaryUnit,
        Rule::pri_are | Rule::sec_are => Atom::Are,
        Rule::pri_astronomic_unit | Rule::sec_astronomic_unit => Atom::AstronomicUnit,
        Rule::pri_bar | Rule::sec_bar => Atom::Bar,
        Rule::pri_barn | Rule::sec_barn => Atom::Barn,
        Rule::pri_barrel_us | Rule::sec_barrel_us => Atom::BarrelUS,
        Rule::pri_baud | Rule::sec_baud => Atom::Baud,
        Rule::pri_becquerel | Rule::sec_becquerel => Atom::Becquerel,
        Rule::pri_bel | Rule::sec_bel => Atom::Bel,
        Rule::pri_bel10_nanovolt | Rule::sec_bel10_nanovolt => Atom::Bel10Nanovolt,
        Rule::pri_bel_kilowatt | Rule::sec_bel_kilowatt => Atom::BelKilowatt,
        Rule::pri_bel_microvolt | Rule::sec_bel_microvolt => Atom::BelMicrovolt,
        Rule::pri_bel_millivolt | Rule::sec_bel_millivolt => Atom::BelMillivolt,
        Rule::pri_bel_sound_pressure | Rule::sec_bel_sound_pressure => Atom::BelSoundPressure,
        Rule::pri_bel_volt | Rule::sec_bel_volt => Atom::BelVolt,
        Rule::pri_bel_watt | Rule::sec_bel_watt => Atom::BelWatt,
        Rule::pri_bethesda_unit | Rule::sec_bethesda_unit => Atom::BethesdaUnit,
        Rule::pri_bioequivalent_allergen_unit | Rule::sec_bioequivalent_allergen_unit => {
            Atom::BioequivalentAllergenUnit
        }
        Rule::pri_biot | Rule::sec_biot => Atom::Biot,
        Rule::pri_bit | Rule::sec_bit => Atom::Bit,
        Rule::pri_bit_logarithmus_dualis | Rule::sec_bit_logarithmus_dualis => {
            Atom::BitLogarithmusDualis
        }
        Rule::pri_board_foot_international | Rule::sec_board_foot_international => {
            Atom::BoardFootInternational
        }
        Rule::pri_bodansky_unit | Rule::sec_bodansky_unit => Atom::BodanskyUnit,
        Rule::pri_boltzmann_constant | Rule::sec_boltzmann_constant => Atom::BoltzmannConstant,
        Rule::pri_british_thermal_unit | Rule::sec_british_thermal_unit => Atom::BritishThermalUnit,
        Rule::pri_british_thermal_unit_at39_f | Rule::sec_british_thermal_unit_at39_f => {
            Atom::BritishThermalUnitAt39F
        }
        Rule::pri_british_thermal_unit_at59_f | Rule::sec_british_thermal_unit_at59_f => {
            Atom::BritishThermalUnitAt59F
        }
        Rule::pri_british_thermal_unit_at60_f | Rule::sec_british_thermal_unit_at60_f => {
            Atom::BritishThermalUnitAt60F
        }
        Rule::pri_bushel_british | Rule::sec_bushel_british => Atom::BushelBritish,
        Rule::pri_bushel_us | Rule::sec_bushel_us => Atom::BushelUS,
        Rule::pri_byte | Rule::sec_byte => Atom::Byte,
        Rule::pri_calorie | Rule::sec_calorie => Atom::Calorie,
        Rule::pri_calorie_at15_c | Rule::sec_calorie_at15_c => Atom::CalorieAt15C,
        Rule::pri_calorie_at20_c | Rule::sec_calorie_at20_c => Atom::CalorieAt20C,
        Rule::pri_candela | Rule::sec_candela => Atom::Candela,
        Rule::pri_carat_of_gold_alloys | Rule::sec_carat_of_gold_alloys => Atom::CaratOfGoldAlloys,
        Rule::pri_cell_culture_infectious_dose | Rule::sec_cell_culture_infectious_dose => {
            Atom::CellCultureInfectiousDose
        }
        Rule::pri_charriere | Rule::sec_charriere => Atom::Charriere,
        Rule::pri_cicero | Rule::sec_cicero => Atom::Cicero,
        Rule::pri_circle | Rule::sec_circle => Atom::Circle,
        Rule::pri_circular_mil_international | Rule::sec_circular_mil_international => {
            Atom::CircularMilInternational
        }
        Rule::pri_colony_forming_units | Rule::sec_colony_forming_units => Atom::ColonyFormingUnits,
        Rule::pri_cord_international | Rule::sec_cord_international => Atom::CordInternational,
        Rule::pri_cord_us | Rule::sec_cord_us => Atom::CordUS,
        Rule::pri_coulomb | Rule::sec_coulomb => Atom::Coulomb,
        Rule::pri_cubic_foot_international | Rule::sec_cubic_foot_international => {
            Atom::CubicFootInternational
        }
        Rule::pri_cubic_inch_international | Rule::sec_cubic_inch_international => {
            Atom::CubicInchInternational
        }
        Rule::pri_cubic_yard_international | Rule::sec_cubic_yard_international => {
            Atom::CubicYardInternational
        }
        Rule::pri_cup_us | Rule::sec_cup_us => Atom::CupUS,
        Rule::pri_curie | Rule::sec_curie => Atom::Curie,
        Rule::pri_d_antigen_unit | Rule::sec_d_antigen_unit => Atom::DAntigenUnit,
        Rule::pri_day | Rule::sec_day => Atom::Day,
        Rule::pri_degree | Rule::sec_degree => Atom::Degree,
        Rule::pri_degree_celsius | Rule::sec_degree_celsius => Atom::DegreeCelsius,
        Rule::pri_degree_fahrenheit | Rule::sec_degree_fahrenheit => Atom::DegreeFahrenheit,
        Rule::pri_degree_rankine | Rule::sec_degree_rankine => Atom::DegreeRankine,
        Rule::pri_degree_reaumur | Rule::sec_degree_reaumur => Atom::DegreeReaumur,
        Rule::pri_denier | Rule::sec_denier => Atom::Denier,
        Rule::pri_didot | Rule::sec_didot => Atom::Didot,
        Rule::pri_diopter | Rule::sec_diopter => Atom::Diopter,
        Rule::pri_dram_apothecaries | Rule::sec_dram_apothecaries => Atom::DramApothecaries,
        Rule::pri_dram_avoirdupois | Rule::sec_dram_avoirdupois => Atom::DramAvoirdupois,
        Rule::pri_drop | Rule::sec_drop => Atom::Drop,
        Rule::pri_dry_pint_us | Rule::sec_dry_pint_us => Atom::DryPintUS,
        Rule::pri_dry_quart_us | Rule::sec_dry_quart_us => Atom::DryQuartUS,
        Rule::pri_dye_unit | Rule::sec_dye_unit => Atom::DyeUnit,
        Rule::pri_dyne | Rule::sec_dyne => Atom::Dyne,
        Rule::pri_ehrlich_unit | Rule::sec_ehrlich_unit => Atom::EhrlichUnit,
        Rule::pri_electron_mass | Rule::sec_electron_mass => Atom::ElectronMass,
        Rule::pri_electronvolt | Rule::sec_electronvolt => Atom::Electronvolt,
        Rule::pri_elementary_charge | Rule::sec_elementary_charge => Atom::ElementaryCharge,
        Rule::pri_elisa_unit | Rule::sec_elisa_unit => Atom::ElisaUnit,
        Rule::pri_embryo_infectious_dose | Rule::sec_embryo_infectious_dose => {
            Atom::EmbryoInfectiousDose
        }
        Rule::pri_equivalents | Rule::sec_equivalents => Atom::Equivalents,
        Rule::pri_erg | Rule::sec_erg => Atom::Erg,
        Rule::pri_farad | Rule::sec_farad => Atom::Farad,
        Rule::pri_fathom_british | Rule::sec_fathom_british => Atom::FathomBritish,
        Rule::pri_fathom_international | Rule::sec_fathom_international => {
            Atom::FathomInternational
        }
        Rule::pri_fathom_us | Rule::sec_fathom_us => Atom::FathomUS,
        Rule::pri_fibrinogen_equivalent_unit | Rule::sec_fibrinogen_equivalent_unit => {
            Atom::FibrinogenEquivalentUnit
        }
        Rule::pri_fluid_dram_british | Rule::sec_fluid_dram_british => Atom::FluidDramBritish,
        Rule::pri_fluid_dram_us | Rule::sec_fluid_dram_us => Atom::FluidDramUS,
        Rule::pri_fluid_ounce_british | Rule::sec_fluid_ounce_british => Atom::FluidOunceBritish,
        Rule::pri_fluid_ounce_us | Rule::sec_fluid_ounce_us => Atom::FluidOunceUS,
        Rule::pri_focus_forming_units | Rule::sec_focus_forming_units => Atom::FocusFormingUnits,
        Rule::pri_foot_british | Rule::sec_foot_british => Atom::FootBritish,
        Rule::pri_foot_international | Rule::sec_foot_international => Atom::FootInternational,
        Rule::pri_foot_us | Rule::sec_foot_us => Atom::FootUS,
        Rule::pri_furlong_us | Rule::sec_furlong_us => Atom::FurlongUS,
        Rule::pri_gal | Rule::sec_gal => Atom::Gal,
        Rule::pri_gallon_british | Rule::sec_gallon_british => Atom::GallonBritish,
        Rule::pri_gauss | Rule::sec_gauss => Atom::Gauss,
        Rule::pri_gilbert | Rule::sec_gilbert => Atom::Gilbert,
        Rule::pri_gill_british | Rule::sec_gill_british => Atom::GillBritish,
        Rule::pri_gill_us | Rule::sec_gill_us => Atom::GillUS,
        Rule::pri_gon | Rule::sec_gon => Atom::Gon,
        Rule::pri_gpl_unit | Rule::sec_gpl_unit => Atom::GplUnit,
        Rule::pri_grain | Rule::sec_grain => Atom::Grain,
        Rule::pri_gram | Rule::sec_gram => Atom::Gram,
        Rule::pri_gram_force | Rule::sec_gram_force => Atom::GramForce,
        Rule::pri_gram_percent | Rule::sec_gram_percent => Atom::GramPercent,
        Rule::pri_gray | Rule::sec_gray => Atom::Gray,
        Rule::pri_gunters_chain_british | Rule::sec_gunters_chain_british => {
            Atom::GuntersChainBritish
        }
        Rule::pri_gunters_chain_us | Rule::sec_gunters_chain_us => Atom::GuntersChainUS,
        Rule::pri_hand_international | Rule::sec_hand_international => Atom::HandInternational,
        Rule::pri_henry | Rule::sec_henry => Atom::Henry,
        Rule::pri_hertz | Rule::sec_hertz => Atom::Hertz,
        Rule::pri_high_power_field | Rule::sec_high_power_field => Atom::HighPowerField,
        Rule::pri_historical_winchester_gallon | Rule::sec_historical_winchester_gallon => {
            Atom::HistoricalWinchesterGallon
        }
        Rule::pri_homeopathic_potency_of_centesimal_hahnemannian_series
        | Rule::sec_homeopathic_potency_of_centesimal_hahnemannian_series => {
            Atom::HomeopathicPotencyOfCentesimalHahnemannianSeries
        }
        Rule::pri_homeopathic_potency_of_centesimal_korsakovian_series
        | Rule::sec_homeopathic_potency_of_centesimal_korsakovian_series => {
            Atom::HomeopathicPotencyOfCentesimalKorsakovianSeries
        }
        Rule::pri_homeopathic_potency_of_centesimal_series_retired
        | Rule::sec_homeopathic_potency_of_centesimal_series_retired => {
            Atom::HomeopathicPotencyOfCentesimalSeriesRetired
        }
        Rule::pri_homeopathic_potency_of_decimal_hahnemannian_series
        | Rule::sec_homeopathic_potency_of_decimal_hahnemannian_series => {
            Atom::HomeopathicPotencyOfDecimalHahnemannianSeries
        }
        Rule::pri_homeopathic_potency_of_decimal_korsakovian_series
        | Rule::sec_homeopathic_potency_of_decimal_korsakovian_series => {
            Atom::HomeopathicPotencyOfDecimalKorsakovianSeries
        }
        Rule::pri_homeopathic_potency_of_decimal_series_retired
        | Rule::sec_homeopathic_potency_of_decimal_series_retired => {
            Atom::HomeopathicPotencyOfDecimalSeriesRetired
        }
        Rule::pri_homeopathic_potency_of_millesimal_hahnemannian_series
        | Rule::sec_homeopathic_potency_of_millesimal_hahnemannian_series => {
            Atom::HomeopathicPotencyOfMillesimalHahnemannianSeries
        }
        Rule::pri_homeopathic_potency_of_millesimal_korsakovian_series
        | Rule::sec_homeopathic_potency_of_millesimal_korsakovian_series => {
            Atom::HomeopathicPotencyOfMillesimalKorsakovianSeries
        }
        Rule::pri_homeopathic_potency_of_millesimal_series_retired
        | Rule::sec_homeopathic_potency_of_millesimal_series_retired => {
            Atom::HomeopathicPotencyOfMillesimalSeriesRetired
        }
        Rule::pri_homeopathic_potency_of_quintamillesimal_hahnemannian_series
        | Rule::sec_homeopathic_potency_of_quintamillesimal_hahnemannian_series => {
            Atom::HomeopathicPotencyOfQuintamillesimalHahnemannianSeries
        }
        Rule::pri_homeopathic_potency_of_quintamillesimal_korsakovian_series
        | Rule::sec_homeopathic_potency_of_quintamillesimal_korsakovian_series => {
            Atom::HomeopathicPotencyOfQuintamillesimalKorsakovianSeries
        }
        Rule::pri_homeopathic_potency_of_quintamillesimal_series_retired
        | Rule::sec_homeopathic_potency_of_quintamillesimal_series_retired => {
            Atom::HomeopathicPotencyOfQuintamillesimalSeriesRetired
        }
        Rule::pri_horsepower | Rule::sec_horsepower => Atom::Horsepower,
        Rule::pri_hounsfield_unit | Rule::sec_hounsfield_unit => Atom::HounsfieldUnit,
        Rule::pri_hour | Rule::sec_hour => Atom::Hour,
        Rule::pri_inch_british | Rule::sec_inch_british => Atom::InchBritish,
        Rule::pri_inch_international | Rule::sec_inch_international => Atom::InchInternational,
        Rule::pri_inch_of_mercury_column | Rule::sec_inch_of_mercury_column => {
            Atom::InchOfMercuryColumn
        }
        Rule::pri_inch_of_water_column | Rule::sec_inch_of_water_column => Atom::InchOfWaterColumn,
        Rule::pri_inch_us | Rule::sec_inch_us => Atom::InchUS,
        Rule::pri_index_of_reactivity | Rule::sec_index_of_reactivity => Atom::IndexOfReactivity,
        Rule::pri_international_table_british_thermal_unit
        | Rule::sec_international_table_british_thermal_unit => {
            Atom::InternationalTableBritishThermalUnit
        }
        Rule::pri_international_table_calorie | Rule::sec_international_table_calorie => {
            Atom::InternationalTableCalorie
        }
        Rule::pri_international_unit | Rule::sec_international_unit => Atom::InternationalUnit,
        Rule::pri_international_unit_secondary | Rule::sec_international_unit_secondary => {
            Atom::InternationalUnitSecondary
        }
        Rule::pri_joule | Rule::sec_joule => Atom::Joule,
        Rule::pri_katal | Rule::sec_katal => Atom::Katal,
        Rule::pri_kayser | Rule::sec_kayser => Atom::Kayser,
        Rule::pri_kelvin | Rule::sec_kelvin => Atom::Kelvin,
        Rule::pri_king_armstrong_unit | Rule::sec_king_armstrong_unit => Atom::KingArmstrongUnit,
        Rule::pri_knot_british | Rule::sec_knot_british => Atom::KnotBritish,
        Rule::pri_knot_international | Rule::sec_knot_international => Atom::KnotInternational,
        Rule::pri_kunkel_unit | Rule::sec_kunkel_unit => Atom::KunkelUnit,
        Rule::pri_lambert | Rule::sec_lambert => Atom::Lambert,
        Rule::pri_light_year | Rule::sec_light_year => Atom::LightYear,
        Rule::pri_ligne | Rule::sec_ligne => Atom::Ligne,
        Rule::pri_limit_of_flocculation | Rule::sec_limit_of_flocculation => {
            Atom::LimitOfFlocculation
        }
        Rule::pri_line | Rule::sec_line => Atom::Line,
        Rule::pri_link_for_gunters_chain_british | Rule::sec_link_for_gunters_chain_british => {
            Atom::LinkForGuntersChainBritish
        }
        Rule::pri_link_for_gunters_chain_us | Rule::sec_link_for_gunters_chain_us => {
            Atom::LinkForGuntersChainUS
        }
        Rule::pri_link_for_ramdens_chain_us | Rule::sec_link_for_ramdens_chain_us => {
            Atom::LinkForRamdensChainUS
        }
        Rule::pri_liter | Rule::sec_liter => Atom::Liter,
        Rule::pri_liter_secondary => Atom::LiterSecondary,
        Rule::pri_long_hunderdweight_avoirdupois | Rule::sec_long_hunderdweight_avoirdupois => {
            Atom::LongHunderdweightAvoirdupois
        }
        Rule::pri_long_ton_avoirdupois | Rule::sec_long_ton_avoirdupois => Atom::LongTonAvoirdupois,
        Rule::pri_low_power_field | Rule::sec_low_power_field => Atom::LowPowerField,
        Rule::pri_lumen | Rule::sec_lumen => Atom::Lumen,
        Rule::pri_lux | Rule::sec_lux => Atom::Lux,
        Rule::pri_mac_lagan_unit | Rule::sec_mac_lagan_unit => Atom::MacLaganUnit,
        Rule::pri_maxwell | Rule::sec_maxwell => Atom::Maxwell,
        Rule::pri_mean_british_thermal_unit | Rule::sec_mean_british_thermal_unit => {
            Atom::MeanBritishThermalUnit
        }
        Rule::pri_mean_calorie | Rule::sec_mean_calorie => Atom::MeanCalorie,
        Rule::pri_mean_gregorian_month | Rule::sec_mean_gregorian_month => Atom::MeanGregorianMonth,
        Rule::pri_mean_gregorian_year | Rule::sec_mean_gregorian_year => Atom::MeanGregorianYear,
        Rule::pri_mean_julian_month | Rule::sec_mean_julian_month => Atom::MeanJulianMonth,
        Rule::pri_mean_julian_year | Rule::sec_mean_julian_year => Atom::MeanJulianYear,
        Rule::pri_mesh_international | Rule::sec_mesh_international => Atom::MeshInternational,
        Rule::pri_metabolic_equivalent | Rule::sec_metabolic_equivalent => {
            Atom::MetabolicEquivalent
        }
        Rule::pri_meter | Rule::sec_meter => Atom::Meter,
        Rule::pri_meter_of_mercury_column | Rule::sec_meter_of_mercury_column => {
            Atom::MeterOfMercuryColumn
        }
        Rule::pri_meter_of_water_column | Rule::sec_meter_of_water_column => {
            Atom::MeterOfWaterColumn
        }
        Rule::pri_meter_per_square_seconds_per_square_root_of_hertz
        | Rule::sec_meter_per_square_seconds_per_square_root_of_hertz => {
            Atom::MeterPerSquareSecondsPerSquareRootOfHertz
        }
        Rule::pri_metric_carat | Rule::sec_metric_carat => Atom::MetricCarat,
        Rule::pri_metric_cup | Rule::sec_metric_cup => Atom::MetricCup,
        Rule::pri_metric_fluid_ounce | Rule::sec_metric_fluid_ounce => Atom::MetricFluidOunce,
        Rule::pri_metric_ounce | Rule::sec_metric_ounce => Atom::MetricOunce,
        Rule::pri_metric_tablespoon | Rule::sec_metric_tablespoon => Atom::MetricTablespoon,
        Rule::pri_metric_teaspoon | Rule::sec_metric_teaspoon => Atom::MetricTeaspoon,
        Rule::pri_mho | Rule::sec_mho => Atom::Mho,
        Rule::pri_mil_international | Rule::sec_mil_international => Atom::MilInternational,
        Rule::pri_mil_us | Rule::sec_mil_us => Atom::MilUS,
        Rule::pri_mile_british | Rule::sec_mile_british => Atom::MileBritish,
        Rule::pri_mile_international | Rule::sec_mile_international => Atom::MileInternational,
        Rule::pri_mile_us | Rule::sec_mile_us => Atom::MileUS,
        Rule::pri_minim_british | Rule::sec_minim_british => Atom::MinimBritish,
        Rule::pri_minim_us | Rule::sec_minim_us => Atom::MinimUS,
        Rule::pri_minute | Rule::sec_minute => Atom::Minute,
        Rule::pri_minute_angle | Rule::sec_minute_angle => Atom::MinuteAngle,
        Rule::pri_mole | Rule::sec_mole => Atom::Mole,
        Rule::pri_month | Rule::sec_month => Atom::Month,
        Rule::pri_mpl_unit | Rule::sec_mpl_unit => Atom::MplUnit,
        Rule::pri_nautical_mile_british | Rule::sec_nautical_mile_british => {
            Atom::NauticalMileBritish
        }
        Rule::pri_nautical_mile_international | Rule::sec_nautical_mile_international => {
            Atom::NauticalMileInternational
        }
        Rule::pri_neper | Rule::sec_neper => Atom::Neper,
        Rule::pri_newton | Rule::sec_newton => Atom::Newton,
        Rule::pri_newtonian_constant_of_gravitation
        | Rule::sec_newtonian_constant_of_gravitation => Atom::NewtonianConstantOfGravitation,
        Rule::pri_nutrition_label_calories | Rule::sec_nutrition_label_calories => {
            Atom::NutritionLabelCalories
        }
        Rule::pri_oersted | Rule::sec_oersted => Atom::Oersted,
        Rule::pri_ohm | Rule::sec_ohm => Atom::Ohm,
        Rule::pri_osmole | Rule::sec_osmole => Atom::Osmole,
        Rule::pri_ounce_apothecaries | Rule::sec_ounce_apothecaries => Atom::OunceApothecaries,
        Rule::pri_ounce_avoirdupois | Rule::sec_ounce_avoirdupois => Atom::OunceAvoirdupois,
        Rule::pri_ounce_troy | Rule::sec_ounce_troy => Atom::OunceTroy,
        Rule::pri_ph | Rule::sec_ph => Atom::PH,
        Rule::pri_pace_british | Rule::sec_pace_british => Atom::PaceBritish,
        Rule::pri_parsec | Rule::sec_parsec => Atom::Parsec,
        Rule::pri_parts_per_billion | Rule::sec_parts_per_billion => Atom::PartsPerBillion,
        Rule::pri_parts_per_million | Rule::sec_parts_per_million => Atom::PartsPerMillion,
        Rule::pri_parts_per_thousand | Rule::sec_parts_per_thousand => Atom::PartsPerThousand,
        Rule::pri_parts_per_trillion | Rule::sec_parts_per_trillion => Atom::PartsPerTrillion,
        Rule::pri_pascal | Rule::sec_pascal => Atom::Pascal,
        Rule::pri_peck_british | Rule::sec_peck_british => Atom::PeckBritish,
        Rule::pri_peck_us | Rule::sec_peck_us => Atom::PeckUS,
        Rule::pri_pennyweight_troy | Rule::sec_pennyweight_troy => Atom::PennyweightTroy,
        Rule::pri_percent | Rule::sec_percent => Atom::Percent,
        Rule::pri_percent_of_slope | Rule::sec_percent_of_slope => Atom::PercentOfSlope,
        Rule::pri_peripheral_vascular_resistance_unit
        | Rule::sec_peripheral_vascular_resistance_unit => Atom::PeripheralVascularResistanceUnit,
        Rule::pri_permeability_of_vacuum | Rule::sec_permeability_of_vacuum => {
            Atom::PermeabilityOfVacuum
        }
        Rule::pri_permittivity_of_vacuum | Rule::sec_permittivity_of_vacuum => {
            Atom::PermittivityOfVacuum
        }
        Rule::pri_phot | Rule::sec_phot => Atom::Phot,
        Rule::pri_pica | Rule::sec_pica => Atom::Pica,
        Rule::pri_pied | Rule::sec_pied => Atom::Pied,
        Rule::pri_pint_british | Rule::sec_pint_british => Atom::PintBritish,
        Rule::pri_pint_us | Rule::sec_pint_us => Atom::PintUS,
        Rule::pri_planck_constant | Rule::sec_planck_constant => Atom::PlanckConstant,
        Rule::pri_plaque_forming_units | Rule::sec_plaque_forming_units => Atom::PlaqueFormingUnits,
        Rule::pri_point | Rule::sec_point => Atom::Point,
        Rule::pri_poise | Rule::sec_poise => Atom::Poise,
        Rule::pri_pouce | Rule::sec_pouce => Atom::Pouce,
        Rule::pri_pound_apothecaries | Rule::sec_pound_apothecaries => Atom::PoundApothecaries,
        Rule::pri_pound_avoirdupois | Rule::sec_pound_avoirdupois => Atom::PoundAvoirdupois,
        Rule::pri_pound_force_avoirdupois | Rule::sec_pound_force_avoirdupois => {
            Atom::PoundForceAvoirdupois
        }
        Rule::pri_pound_per_sqare_inch | Rule::sec_pound_per_sqare_inch => Atom::PoundPerSqareInch,
        Rule::pri_pound_troy | Rule::sec_pound_troy => Atom::PoundTroy,
        Rule::pri_printers_pica | Rule::sec_printers_pica => Atom::PrintersPica,
        Rule::pri_printers_point | Rule::sec_printers_point => Atom::PrintersPoint,
        Rule::pri_prism_diopter | Rule::sec_prism_diopter => Atom::PrismDiopter,
        Rule::pri_protein_nitrogen_unit | Rule::sec_protein_nitrogen_unit => {
            Atom::ProteinNitrogenUnit
        }
        Rule::pri_proton_mass | Rule::sec_proton_mass => Atom::ProtonMass,
        Rule::pri_quart_british | Rule::sec_quart_british => Atom::QuartBritish,
        Rule::pri_quart_us | Rule::sec_quart_us => Atom::QuartUS,
        Rule::pri_queen_annes_wine_gallon_us | Rule::sec_queen_annes_wine_gallon_us => {
            Atom::QueenAnnesWineGallonUS
        }
        Rule::pri_radian | Rule::sec_radian => Atom::Radian,
        Rule::pri_radiation_absorbed_dose | Rule::sec_radiation_absorbed_dose => {
            Atom::RadiationAbsorbedDose
        }
        Rule::pri_radiation_equivalent_man | Rule::sec_radiation_equivalent_man => {
            Atom::RadiationEquivalentMan
        }
        Rule::pri_ramdens_chain_us | Rule::sec_ramdens_chain_us => Atom::RamdensChainUS,
        Rule::pri_rod_british | Rule::sec_rod_british => Atom::RodBritish,
        Rule::pri_rod_us | Rule::sec_rod_us => Atom::RodUS,
        Rule::pri_roentgen | Rule::sec_roentgen => Atom::Roentgen,
        Rule::pri_scruple_apothecaries | Rule::sec_scruple_apothecaries => {
            Atom::ScrupleApothecaries
        }
        Rule::pri_second | Rule::sec_second => Atom::Second,
        Rule::pri_second_angle | Rule::sec_second_angle => Atom::SecondAngle,
        Rule::pri_section | Rule::sec_section => Atom::Section,
        Rule::pri_short_hundredweight_avoirdupois | Rule::sec_short_hundredweight_avoirdupois => {
            Atom::ShortHundredweightAvoirdupois
        }
        Rule::pri_short_ton_avoirdupois | Rule::sec_short_ton_avoirdupois => {
            Atom::ShortTonAvoirdupois
        }
        Rule::pri_siemens | Rule::sec_siemens => Atom::Siemens,
        Rule::pri_sievert | Rule::sec_sievert => Atom::Sievert,
        Rule::pri_smoot | Rule::sec_smoot => Atom::Smoot,
        Rule::pri_somogyi_unit | Rule::sec_somogyi_unit => Atom::SomogyiUnit,
        Rule::pri_spere | Rule::sec_spere => Atom::Spere,
        Rule::pri_square_foot_international | Rule::sec_square_foot_international => {
            Atom::SquareFootInternational
        }
        Rule::pri_square_inch_international | Rule::sec_square_inch_international => {
            Atom::SquareInchInternational
        }
        Rule::pri_square_mile_us | Rule::sec_square_mile_us => Atom::SquareMileUS,
        Rule::pri_square_rod_us | Rule::sec_square_rod_us => Atom::SquareRodUS,
        Rule::pri_square_yard_international | Rule::sec_square_yard_international => {
            Atom::SquareYardInternational
        }
        Rule::pri_standard_acceleration_of_free_fall
        | Rule::sec_standard_acceleration_of_free_fall => Atom::StandardAccelerationOfFreeFall,
        Rule::pri_standard_atmosphere | Rule::sec_standard_atmosphere => Atom::StandardAtmosphere,
        Rule::pri_steradian | Rule::sec_steradian => Atom::Steradian,
        Rule::pri_stere | Rule::sec_stere => Atom::Stere,
        Rule::pri_stilb | Rule::sec_stilb => Atom::Stilb,
        Rule::pri_stokes | Rule::sec_stokes => Atom::Stokes,
        Rule::pri_stone_avoirdupois | Rule::sec_stone_avoirdupois => Atom::StoneAvoirdupois,
        Rule::pri_svedberg_unit | Rule::sec_svedberg_unit => Atom::SvedbergUnit,
        Rule::pri_synodal_month | Rule::sec_synodal_month => Atom::SynodalMonth,
        Rule::pri_tablespoon_us | Rule::sec_tablespoon_us => Atom::TablespoonUS,
        Rule::pri_teaspoon_us | Rule::sec_teaspoon_us => Atom::TeaspoonUS,
        Rule::pri_technical_atmosphere | Rule::sec_technical_atmosphere => {
            Atom::TechnicalAtmosphere
        }
        Rule::pri_tesla | Rule::sec_tesla => Atom::Tesla,
        Rule::pri_tex | Rule::sec_tex => Atom::Tex,
        Rule::pri_the_number_pi | Rule::sec_the_number_pi => Atom::TheNumberPi,
        Rule::pri_the_number_ten_for_arbitrary_powers_caret
        | Rule::sec_the_number_ten_for_arbitrary_powers_caret => {
            Atom::TheNumberTenForArbitraryPowersCaret
        }
        Rule::pri_the_number_ten_for_arbitrary_powers_star
        | Rule::sec_the_number_ten_for_arbitrary_powers_star => {
            Atom::TheNumberTenForArbitraryPowersStar
        }
        Rule::pri_thermochemical_british_thermal_unit
        | Rule::sec_thermochemical_british_thermal_unit => Atom::ThermochemicalBritishThermalUnit,
        Rule::pri_thermochemical_calorie | Rule::sec_thermochemical_calorie => {
            Atom::ThermochemicalCalorie
        }
        Rule::pri_tissue_culture_infectious_dose | Rule::sec_tissue_culture_infectious_dose => {
            Atom::TissueCultureInfectiousDose
        }
        Rule::pri_todd_unit | Rule::sec_todd_unit => Atom::ToddUnit,
        Rule::pri_tonne | Rule::sec_tonne => Atom::Tonne,
        Rule::pri_township | Rule::sec_township => Atom::Township,
        Rule::pri_tropical_year | Rule::sec_tropical_year => Atom::TropicalYear,
        Rule::pri_tuberculin_unit | Rule::sec_tuberculin_unit => Atom::TuberculinUnit,
        Rule::pri_unified_atomic_mass_unit | Rule::sec_unified_atomic_mass_unit => {
            Atom::UnifiedAtomicMassUnit
        }
        Rule::pri_unit | Rule::sec_unit => Atom::Unit,
        Rule::pri_united_states_pharmacopeia_unit | Rule::sec_united_states_pharmacopeia_unit => {
            Atom::UnitedStatesPharmacopeiaUnit
        }
        Rule::pri_velocity_of_light | Rule::sec_velocity_of_light => Atom::VelocityOfLight,
        Rule::pri_volt | Rule::sec_volt => Atom::Volt,
        Rule::pri_watt | Rule::sec_watt => Atom::Watt,
        Rule::pri_weber | Rule::sec_weber => Atom::Weber,
        Rule::pri_week | Rule::sec_week => Atom::Week,
        Rule::pri_wood_unit | Rule::sec_wood_unit => Atom::WoodUnit,
        Rule::pri_yard_british | Rule::sec_yard_british => Atom::YardBritish,
        Rule::pri_yard_international | Rule::sec_yard_international => Atom::YardInternational,
        Rule::pri_yard_us | Rule::sec_yard_us => Atom::YardUS,
        Rule::pri_year | Rule::sec_year => Atom::Year,
        _ => return Err(Error::UnknownUnitString(pair.as_str().to_string())),
    };

    Ok(atom)
}

fn visit_prefix(pair: &Pair<'_, Rule>) -> Result<Prefix, Error> {
    let prefix = match pair.as_rule() {
        Rule::pri_atto | Rule::sec_atto => Prefix::Atto,
        Rule::pri_centi | Rule::sec_centi => Prefix::Centi,
        Rule::pri_deci | Rule::sec_deci => Prefix::Deci,
        Rule::pri_deka | Rule::sec_deka => Prefix::Deka,
        Rule::pri_exa | Rule::sec_exa => Prefix::Exa,
        Rule::pri_femto | Rule::sec_femto => Prefix::Femto,
        Rule::pri_gibi | Rule::sec_gibi => Prefix::Gibi,
        Rule::pri_giga | Rule::sec_giga => Prefix::Giga,
        Rule::pri_hecto | Rule::sec_hecto => Prefix::Hecto,
        Rule::pri_kilo | Rule::sec_kilo => Prefix::Kilo,
        Rule::pri_mebi | Rule::sec_mebi => Prefix::Mebi,
        Rule::pri_mega | Rule::sec_mega => Prefix::Mega,
        Rule::pri_micro | Rule::sec_micro => Prefix::Micro,
        Rule::pri_milli | Rule::sec_milli => Prefix::Milli,
        Rule::pri_nano | Rule::sec_nano => Prefix::Nano,
        Rule::pri_peta | Rule::sec_peta => Prefix::Peta,
        Rule::pri_tebi | Rule::sec_tebi => Prefix::Tebi,
        Rule::pri_tera | Rule::sec_tera => Prefix::Tera,
        Rule::pri_yocto | Rule::sec_yocto => Prefix::Yocto,
        Rule::pri_yotta | Rule::sec_yotta => Prefix::Yotta,
        Rule::pri_zepto | Rule::sec_zepto => Prefix::Zepto,
        Rule::pri_zetta | Rule::sec_zetta => Prefix::Zetta,
        _ => return Err(Error::UnknownUnitString(pair.as_str().to_string())),
    };

    Ok(prefix)
}
